from setuptools import setup, find_packages
setup(
    name="weather",
    version="1.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'Click',
        'pytz',
        'tksheet',
        'tkcalendar',
        'requests',
        'pyYAML',
        'fastapi',
        'pydantic',
        'uvicorn',
        'python-multipart',
        'pyjwt',
        'passlib[bcrypt]',
        'orjson',
        'sqlalchemy'
    ],
    entry_points='''
        [console_scripts]
        wgui=weather.gui:run_gui
        wcli=weather.cli:run_cli
        wserver=weather.server:run_server
        dbload=weather.db.tools:db_load
        dbcli=weather.db.tools:cli
    ''',
)
