# Unfortunately the typing information is needed to make sure PyCharm can grok
# PyO3 bindings. It would be nice if PyO3 would mine this from the Rust documentation
# however it looks like that project has been put on hold.
#
# Another issue is PyCharm doesn't use any typing information from the interface. So
# the best you can see from the IDE is the bare function definition and return types.
#
from datetime import date, datetime
from typing import List


def create(config: PyWeatherConfig) -> PyWeatherData: ...


class PyWeatherData:
    def add_histories(self, daily_histories: PyDailyHistories) -> int: ...

    def new_daily_histories(self, filter: PyLocationFilter, dates: PyDateRange) -> PyHistoriesFuture: ...

    def get_daily_histories(self, filter: PyLocationFilter, date_range: PyDateRange) -> PyDailyHistories: ...

    def get_history_dates(self, filters: PyLocationFilters) -> List[PyHistoryDates]: ...

    def get_history_summaries(self, filters: PyLocationFilters) -> List[PyHistorySummary]: ...

    def get_locations(self, filters: PyLocationFilters) -> List[PyLocation]: ...

    def add_location(self, location: PyLocation) -> None: ...

    def get_cities(self, filter: PyLocationFilter, limit: int) -> List[PyLocation]: ...

    def get_states(self) -> List[PyState]: ...


class PyWeatherConfig:
    @property
    def config_file(self) -> str | None: ...

    @config_file.setter
    def config_file(self, str) -> None: ...

    @property
    def dirname(self) -> str | None: ...

    @dirname.setter
    def dirname(self, str) -> None: ...

    @property
    def logfile(self) -> str | None: ...

    @logfile.setter
    def logfile(self, str) -> None: ...

    @property
    def log_append(self) -> bool: ...

    @log_append.setter
    def logfile(self, bool) -> None: ...

    @property
    def log_level(self) -> int: ...

    @log_level.setter
    def log_level(self, int) -> None: ...

    @property
    def fs_only(self) -> bool: ...

    @fs_only.setter
    def fs_only(self, bool) -> None: ...

    def __new__(
            cls,
            config_file: str | None = None,
            dirname: str | None = None,
            logfile: str | None = None,
            log_append=False,
            log_level=0,
            fs_only=False,
    ) -> PyWeatherConfig: ...


class PyHistoriesFuture:

    def is_finished(self) -> bool: ...

    def get(self) -> PyDailyHistories: ...


class PyLocation:
    @property
    def country_name(self) -> str | None: ...

    @country_name.setter
    def country_name(self, str) -> None: ...

    @property
    def country_code(self) -> str | None: ...

    @country_code.setter
    def country_code(self, str) -> None: ...

    @property
    def region_name(self) -> str | None: ...

    @region_name.setter
    def region_name(self, str) -> None: ...

    @property
    def region_code(self) -> str | None: ...

    @region_code.setter
    def region_code(self, str) -> None: ...

    @property
    def city_name(self) -> str | None: ...

    @city_name.setter
    def city_name(self, str) -> None: ...

    @property
    def alias(self) -> str | None: ...

    @alias.setter
    def alias(self, str) -> None: ...

    @property
    def longitude(self) -> str | None: ...

    @longitude.setter
    def longitude(self, str) -> None: ...

    @property
    def latitude(self) -> str | None: ...

    @latitude.setter
    def latitude(self, str) -> None: ...

    @property
    def tz(self) -> str | None: ...

    @tz.setter
    def tz(self, str) -> None: ...

    def __new__(
            cls,
            city_name: str | None = None,
            country_name: str | None = None,
            country_code: str | None = None,
            region_name: str | None = None,
            region_code: str | None = None,
            alias: str | None = None,
            latitude: str | None = None,
            longitude: str | None = None,
            tz: str | None = None,
    ) -> PyLocation: ...


class PyHistory:
    @property
    def alias(self) -> str: ...

    @alias.setter
    def alias(self, str) -> None: ...

    @property
    def date(self) -> date: ...

    @date.setter
    def alias(self, date) -> None: ...

    @property
    def temperature_high(self) -> float | None: ...

    @temperature_high.setter
    def temperature_high(self, high: float | None) -> None: ...

    @property
    def temperature_low(self) -> float | None: ...

    @temperature_low.setter
    def temperature_low(self, low: float | None) -> None: ...

    @property
    def temperature_mean(self) -> float | None: ...

    @temperature_mean.setter
    def temperature_mean(self, mean: float | None) -> None: ...

    @property
    def dew_point(self) -> float | None: ...

    @dew_point.setter
    def dew_point(self, dew_point: float | None) -> None: ...

    @property
    def humidity(self) -> float | None: ...

    @humidity.setter
    def humidity(self, humidity: float | None) -> None: ...

    @property
    def precipitation_chance(self) -> float | None: ...

    @precipitation_chance.setter
    def precipitation_chance(self, precip_chance: float | None) -> None: ...

    @property
    def precipitation_type(self) -> str | None: ...

    @precipitation_type.setter
    def precipitation_type(self, precip_type: str | None) -> None: ...

    @property
    def precipitation_amount(self) -> float | None: ...

    @precipitation_amount.setter
    def precipitation_amount(self, precip_amount: float | None) -> None: ...

    @property
    def wind_speed(self) -> float | None: ...

    @wind_speed.setter
    def wind_speed(self, speed: float | None) -> None: ...

    @property
    def wind_gust(self) -> float | None: ...

    @wind_gust.setter
    def wind_gust(self, gust: float | None) -> None: ...

    @property
    def wind_direction(self) -> float | None: ...

    @wind_direction.setter
    def wind_direction(self, direction: float | None) -> None: ...

    @property
    def cloud_cover(self) -> float | None: ...

    @cloud_cover.setter
    def cloud_cover(self, cover: float | None) -> None: ...

    @property
    def pressure(self) -> float | None: ...

    @pressure.setter
    def pressure(self, pressure: float | None) -> None: ...

    @property
    def uv_index(self) -> float | None: ...

    @uv_index.setter
    def uv_index(self, index: float | None) -> None: ...

    @property
    def sunrise(self) -> datetime | None: ...

    @sunrise.setter
    def sunrise(self, when: datetime | None) -> None: ...

    @property
    def sunset(self) -> datetime | None: ...

    @sunset.setter
    def sunset(self, when: datetime | None) -> None: ...

    @property
    def moon_phase(self) -> float | None: ...

    @moon_phase.setter
    def moon_phase(self, phase: float | None) -> None: ...

    @property
    def visibility(self) -> float | None: ...

    @visibility.setter
    def visibility(self, phase: float | None) -> None: ...

    @property
    def description(self) -> str | None: ...

    @description.setter
    def description(self, descr: str | None) -> None: ...

    def __new__(cls) -> PyHistory: ...

    def wind_direction_str(self) -> str: ...

    def uv_index_str(self) -> str: ...

    def moon_phase_str(self) -> str: ...


class PyDailyHistories:
    @property
    def location(self) -> PyLocation: ...

    @location.setter
    def location(self, location: PyLocation) -> None: ...

    @property
    def histories(self) -> List[PyHistory]: ...

    @histories.setter
    def histories(self, histories: List[PyHistory]) -> None: ...

    def __new__(cls) -> PyDailyHistories: ...


class PyDateRange:
    @property
    def start(self) -> date: ...

    @start.setter
    def start(self, start: date) -> None: ...

    @property
    def end(self) -> date: ...

    @end.setter
    def end(self, end: date) -> None: ...

    def __new__(cls, start: date, end: date) -> PyDateRange: ...

    def annualized(self) -> List[PyDateRange]: ...

    def contains(self, d: date) -> bool: ...

    def is_one_day(self) -> bool: ...

    def is_one_year(self) -> bool: ...

    def is_multi_year(self) -> bool: ...


class PyHistoryDates:
    @property
    def location(self) -> PyLocation: ...

    @property
    def history_dates(self) -> List[PyDateRange]: ...


class PyHistorySummary:
    @property
    def location(self) -> PyLocation: ...

    @property
    def days(self) -> int | None: ...

    @property
    def fs_history_summary(self) -> PyFilesysHistorySummary: ...

    @property
    def db_history_summary(self) -> PyDatabaseHistorySummary | None: ...

    def __new__(cls) -> PyHistorySummary: ...


class PyFilesysHistorySummary:
    @property
    def uncompressed_size(self) -> int: ...

    @property
    def compressed_size(self) -> int: ...

    @property
    def data_size(self) -> int: ...

    @property
    def archive_size(self) -> int: ...

    def __new__(cls) -> PyFilesysHistorySummary: ...


class PyDatabaseHistorySummary:
    @property
    def data_bytes(self) -> int: ...

    @property
    def unused_data_bytes(self) -> int: ...

    @property
    def index_bytes(self) -> int: ...

    @property
    def unused_index_bytes(self) -> int: ...

    def __new__(cls) -> PyDatabaseHistorySummary: ...


class PyLocationFilter:
    @property
    def alias(self) -> str | None: ...

    @alias.setter
    def alias(self, str) -> None: ...

    @property
    def city(self) -> str | None: ...

    @city.setter
    def city(self, str) -> None: ...

    @property
    def region(self) -> str | None: ...

    @region.setter
    def region(self, str) -> None: ...

    @property
    def country(self) -> str | None: ...

    @country.setter
    def country(self, str) -> None: ...

    def __new__(
            cls,
            alias: str | None = None,
            city: str | None = None,
            region: str | None = None,
            country: str | None = None,
    ) -> PyLocationFilter: ...


class PyLocationFilters:
    @property
    def filters(self) -> List[PyLocationFilter]: ...

    @filters.setter
    def filters(self, filters: List[PyLocationFilter]) -> None: ...

    def __new__(
            cls,
            filters=List[PyLocationFilter],
    ) -> PyLocationFilters: ...


class PyState:
    @property
    def name(self) -> str | None: ...

    @name.setter
    def name(self, str) -> None: ...

    @property
    def state_id(self) -> str | None: ...

    @state_id.setter
    def state_id(self, str) -> None: ...
