[workspace]
resolver = "2"

members = [
    "cli",
    "lib",
    "py_lib",
    "termui", "tui",
]

[workspace.dependencies]
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = { version = "0.10", features = ["serde"] }
log = "0.4"
rusqlite = { version = "0.38", features = ["bundled", "chrono"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
toml = { version = "0.9", features = ["preserve_order"] }
toolslib = { path = "../toolslib" }
crossterm = "0.29"
ratatui = { version = "0.30", features = ["all-widgets", "serde"] }
