[package]
name = "toolslib"
version = "0.7.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
chrono-tz = { version = "0.9.0", features = ["serde"] }
log = "0.4"
log4rs = "1.3"
thousands = "0.2"
