newline_style = "Unix"
use_small_heuristics = "Max"
max_width = 120
single_line_if_else_max_width = 100
array_width = 100
wrap_comments = true
comment_width = 100
fn_call_width = 120
fn_single_line = true
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
overflow_delimited_expr = true
reorder_impl_items = true
