[package]
name = "tui_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
crossterm.workspace = true
ratatui.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
toolslib.workspace = true
strum = { version = "0.26", features = ["derive"]}
